version: '3.8'

services:
  release_management_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container
    ports:
      - "3000:3000"
    depends_on:
      mysql_releases_db:
        condition: service_healthy

  mysql_releases_db:
    image: mysql:8.0
    container_name: mysql_container
    # env_file:
    #   - path: ./src/.env
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/releases.sql:/docker-entrypoint-initdb.d/releases.sql
    ports:
      - "3306:3306"
    healthcheck:
    # Reflects the 'service_healthy' condition in the 'app' service 
    # 'mysqladmin' is installed by default in the MySQL image
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
