CREATE DATABASE IF NOT EXISTS top_secret_db;
USE top_secret_db;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


INSERT INTO users (username, password) VALUES ('admin', '${ADMIN_PASSWORD}');
INSERT INTO users (username, password) VALUES ('bart', '${BART_PASSWORD}');

CREATE DATABASE IF NOT EXISTS releases_db;
USE releases_db;

CREATE TABLE IF NOT EXISTS releases (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    version VARCHAR(50) NOT NULL,
    account VARCHAR(255) NOT NULL,
    region VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE USER 'shane'@'%' IDENTIFIED BY '${DB_PASSWORD}';
GRANT SELECT, INSERT, UPDATE ON releases_db.releases TO 'shane'@'%';
FLUSH PRIVILEGES;